# Generated by Django 5.2 on 2025-04-18 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("autenticacao", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="nome",
        ),
        migrations.AddField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
