# Generated by Django 5.2 on 2025-07-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_categorias", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="padrao",
            field=models.BooleanField(
                default=False, help_text="Indica se é uma categoria padrão do sistema"
            ),
        ),
    ]
